### ISSUE TITLE
Server not closing with single signal of SIGINT or SIGTERM

### ISSUE THREAD

**Issue by Dankage102** [opensoldat/opensoldat#142] opened 2022-08-21 23:35 UTC
Tried to kill the server from ARSSE with RAW command SHUTDOWN (similar to SIGTERM(15)) https://wiki.soldat.pl/index.php/Raw_commands
```
[RCON] SHUTDOWN (*.*.*.*).
Shutting down server...
Shutting down game networking.
Shutting down admin server...
[FileServer] Stopping fileserver
```
Stopped right there and didn't want to close it further

Then tried with ctrl+c(SIGINT), had to send the signal few times as You see
```
Control-C hit, shutting down
Shutting down server...
Shutting down game networking.
Shutting down admin server...
[FileServer] Stopping fileserver
^C
OK, OK, exiting immediately
^CAn unhandled exception occurred at $0000000000000000:
EAccessViolation: Access violation
  $0000000000000000

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Aborted (core dumped)
```
Launching it on **screen** with shell script so as You see from the code I expect from the server to restart when it's done shutting down
```
#!/bin/bash
while true
do
	./opensoldatserver
	echo Restarting server in 5s...
	sleep 5
done
```

**Comment by BranDougherty** [comment] 2022-08-22 00:32
There is a problem interrupting `TThread.Destroy` with a signal, which gets the server stuck in `pthread_cond_destroy`, not sure exactly the cause. I just changed the fileserver shutdown code back to something similar to the way it was before, and it works.

This means that `THTTPServer.Destroy` is back to the state it was in before #67 was merged. There is somewhat of a race condition to get the destructor called before the whole server process is cleaned up by the OS. But when the server process is cleaned up, all meaningful resources are freed so I would say it doesn't matter at that point if the destructor finishes or not.

Also, with FPC 3.3.x, there will be a cleaner solution with `TFPCustomHttpServer.ConnectionHandler`, where we can hard shutdown the server without waiting.

**Closed as completed** 2022-08-24 00:46 UTC
